services:
- type: web
  repo: https://github.com/fxhxyz4/TwitchColorChanger.git
  name: color
  runtime: node
  plan: free
  buildCommand: yarn
  startCommand: yarn dep
  region: frankfurt
  branch: main
  envVars:
  - key: PORT
    value: 3000
  - key: USER
    value: awpsdrop
  - key: ID
    value: 1002474040
  - key: CHANNEL
    value: lqgs, awpsdrop
  - key: CLIENT_ID
    value: 0ugyt7963byt91c9i67dposq3f3oc2
  - key: CLIENT_SECRET
    value: 0ugyt7963byt91c9i67dposq3f3oc2
  - key: OAUTH
    value: 72iasr7soqx94pawobtue24pvak12h
  - key: PRIME
    value: "true"
  - key: DELAY
    value: 1
  - key: BASE_URI
    value: http://localhost:3000
  - key: REDIRECT_URI
    value: http://localhost:3000/auth/twitch/callback
  - key: AUTH_URI
    value: https://id.twitch.tv/oauth2
  - key: POST
    value: https://api.twitch.tv/helix/chat/color
